- name: COLLECTOR | Copy collector config
  template:
    src: collector.conf.j2
    dest: /etc/logstash/conf.d/collector.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - logstash
    - ls-config
    - ls-collectorconf
  notify:
    - test logstash config
    - restart logstash

- name: COLLECTOR | Copy logstash SSL certificate
  template:
    src: logstash.crt.j2
    dest: "{{ logstash_ssl_crt_path }}/logstash.crt"
    owner: root
    group: root
    mode: 0644
  tags:
    - logstash
    - ls-config
    - ls-parserconf
    - ls-ssl

- name: COLLECTOR | Copy logstash SSL private key
  template:
    src: logstash.key.j2
    dest: "{{ logstash_ssl_key_path }}/logstash.key"
    owner: logstash
    group: root
    mode: 0600
  tags:
    - logstash
    - ls-config
    - ls-parserconf
    - ls-ssl
