---
- name: Copy logstash repo
  copy: src=logstash-1.4.repo dest=/etc/yum.repos.d/logstash-1.4.repo owner=root group=root mode=0644
  tags: [ "logstash" , "yum" ]

- name: Copy logstash GPG key
  copy: src=GPG-KEY-elasticsearch dest=/etc/pki/rpm-gpg/GPG-KEY-elasticsearch owner=root group=root mode=0644
  tags: [ "logstash" , "yum" ]
  notify: install elasticsearch gpg key