---
- name: Get current Logstash version
  shell: rpm -q logstash | cut -d '-' -f 2
  changed_when: False
  ignore_errors: True
  register: current_logstash_version
  tags:
    - logstash
    - ls-repo

- name: Remove old repos
  file:
    path=/etc/yum.repos.d/logstash-1-{{ item }}.repo
    state=absent
  with_sequence:
    start=1
    end=5
    stride=1
  tags:
    - logstash
    - ls-repo

- name: Remove logstash-contrib
  yum:
    name: logstash-contrib
    state: absent
  when: "{{ current_logstash_version | float }} < 1.5"
  tags:
    - logstash
    - ls-repo

- name: Install logstash repo
  template:
    src: logstash.repo.j2
    dest: /etc/yum.repos.d/logstash.repo
    owner: root
    group: root
    mode: 0644
  tags:
    - logstash
    - ls-repo

- name: Install Elasticsearch GPG key
  rpm_key:
    key: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present
  tags:
    - logstash
    - ls-repo
