- name: SETUP | Install logstash
  yum:
    name: logstash
    state: latest
  tags:
    - logstash
    - ls-plugins

- name: SETUP | Create sincedb directory
  file:
    state: directory
    path: /opt/logstash/sincedb
    owner: logstash
    group: logstash
  tags:
    - logstash

- name: SETUP | Copy logstash sysconfig
  template:
    src: sysconfig-logstash.j2
    dest: /etc/sysconfig/logstash
    owner: root
    group: root
    mode: '0644'
  notify: restart logstash
  tags:
    - logstash
    - ls-config

- name: SETUP | Copy templates
  copy:
    src: templates
    dest: /opt/logstash/
    owner: logstash
    group: logstash
    mode: '0644'
    directory_mode: '0755'
  notify: restart logstash
  tags:
    - logstash
    - ls-config
    - ls-parserconf
    - ls-templates

- name: SETUP | List installed Logstash plugins
  command: /opt/logstash/bin/{{ logstash_plugin_binary }} list
  become: yes
  become_user: logstash
  changed_when: no
  register: logstash_installed_plugins
  when: logstash_plugins is defined
  tags:
    - logstash
    - ls-plugins

- name: SETUP | Install additional Logstash plugins
  command: /opt/logstash/bin/{{ logstash_plugin_binary }} install {{ item }}
  become: yes
  become_user: logstash
  with_items: "{{ logstash_plugins | default([]) }}"
  when: item not in logstash_installed_plugins.stdout_lines
  notify: restart logstash
  tags:
    - logstash
    - ls-plugins

- name: SETUP | Start and enable Logstash
  service:
    name: logstash
    enabled: yes
    state: started
  tags:
    - logstash
