---
- name: Install logstash
  yum: name=logstash state=present
  tags: logstash

- name: Enable Logstash
  service: name=logstash state=started
  tags: logstash

- name: Create logreader group
  group: name=logreader gid=507
  tags: logstash

- name: Enable logstash in sysconfig
  lineinfile: dest=/etc/sysconfig/logstash regexp='^START=' line='START=true' state=present
  tags: [ 'logstash' , 'config' ]

- name: Raise file limit for logstash
  lineinfile: dest=/etc/sysconfig/logstash regexp='^(#)?OPEN_FILES=' line='OPEN_FILES=65536' state=present
  tags: [ 'logstash' , 'config' ]