---
- name: Install logstash
  yum:
    name: logstash
    state: latest
  tags: logstash

- name: Enable Logstash
  service:
    name: logstash
    enabled: yes
    state: started
  tags: logstash

- name: Set ownership on /var/log/logstash
  file:
    path: /var/log/logstash
    owner: logstash
    group: logstash
    recurse: yes
  tags: logstash

- name: Create logreader group
  group:
    name: logreader
    gid: 520
  tags: logstash

- name: Create sincedb directory
  file:
    state: directory
    path: /opt/logstash/sincedb
    owner: logstash
    group: logstash
  tags: logstash

- name: Add logstash to logreader group
  user:
    name: logstash
    append: yes
    groups: logreader
  tags: logstash

- name: Copy logstash sysconfig
  template:
    src: sysconfig-logstash.j2
    dest: /etc/sysconfig/logstash
    owner: root
    group: root
    mode: 0644
  tags: [ 'logstash' , 'config' ]
  notify: restart logstash

- name: Copy templates
  copy:
    src: templates
    dest: /opt/logstash/
    owner: logstash
    group: logreader
    mode: 0644
    directory_mode: 0755
  notify: restart logstash
  tags: [ "logstash" , "config" , "parserconf" , "templates" ]

- name: List installed Logstash plugins
  command: /opt/logstash/bin/plugin list
  become_user: logstash
  changed_when: False
  register: logstash_installed_plugins
  tags: [ "logstash" , "lsplugins" ]
  when: logstash_plugins is defined

- name: Install additional Logstash plugins
  command: /opt/logstash/bin/plugin install {{ item }}
  become_user: logstash
  with_items: logstash_plugins
  when: "logstash_plugins is defined and '{{ item }}' not in logstash_installed_plugins.stdout_lines"
  tags: [ "logstash" , "lsplugins" ]
  notify: restart logstash
