---
- name: Install logstash
  yum: name=logstash state=latest
  tags: logstash

- name: Enable Logstash
  service: name=logstash enabled=yes state=started
  tags: logstash

- name: Set ownership on /var/log/logstash
  file: path=/var/log/logstash owner=logstash group=logstash recurse=yes
  tags: logstash

- name: Create logreader group
  group: name=logreader gid=520
  tags: logstash

- name: Add logstash to logreader group
  user: name=logstash append=yes groups=logreader
  tags: logstash

- name: Raise file limit for logstash
  lineinfile: dest=/etc/sysconfig/logstash regexp='^(#)?LS_OPEN_FILES=' line='LS_OPEN_FILES=65536' state=present
  tags: [ 'logstash' , 'config' ]
