---
- name: Install logstash
  yum:
    name: logstash
    state: latest
  tags:
    - logstash
    - ls-plugins

- name: Set ownership on /var/log/logstash
  file:
    path: /var/log/logstash
    owner: logstash
    group: logstash
    recurse: yes
  tags:
    - logstash

- name: Create logreader group
  group:
    name: logreader
    gid: 520
  tags:
    - logstash

- name: Create sincedb directory
  file:
    state: directory
    path: /opt/logstash/sincedb
    owner: logstash
    group: logstash
  tags:
    - logstash

- name: Add logstash to logreader group
  user:
    name: logstash
    append: yes
    groups: logreader
  tags:
    - logstash

- name: Copy logstash sysconfig
  template:
    src: sysconfig-logstash.j2
    dest: /etc/sysconfig/logstash
    owner: root
    group: root
    mode: 0644
  notify: restart logstash
  tags:
    - logstash
    - ls-config

- name: Copy templates
  copy:
    src: templates
    dest: /opt/logstash/
    owner: logstash
    group: logreader
    mode: 0644
    directory_mode: 0755
  notify: restart logstash
  tags:
    - logstash
    - ls-config
    - ls-parserconf
    - ls-templates

- name: List installed Logstash plugins
  command: /opt/logstash/bin/{{ logstash_plugin_binary }} list
  become_user: logstash
  changed_when: False
  register: logstash_installed_plugins
  when: logstash_plugins is defined
  tags:
    - logstash
    - ls-plugins

- name: Install additional Logstash plugins
  command: /opt/logstash/bin/{{ logstash_plugin_binary }} install {{ item }}
  become_user: logstash
  with_items: "{{ logstash_plugins }}"
  when: "logstash_plugins is defined and '{{ item }}' not in logstash_installed_plugins.stdout_lines"
  notify: restart logstash
  tags:
    - logstash
    - ls-plugins

- name: Start and enable Logstash
  service:
    name: logstash
    enabled: yes
    state: started
  tags:
    - logstash
