- name: Configure Logstash repo
  import_tasks: ls_repo.yml

- name: Install and configure Logstash
  import_tasks: ls_setup.yml

- name: Configure parsing nodes
  include_tasks: parser.yml
  when: '"ls_parser" in group_names'

- name: Configure collector nodes
  include_tasks: collector.yml
  when: '"ls_collector" in group_names'
