---
- name: Install packages
  yum: name={{ item }} state=present
  tags: packages
  with_items:
    - java-1.8.0-openjdk

- include: ls_repo.yml
- include: ls_setup.yml
- { include: parser.yml, when: '"ls_parser" in group_names'}
- { include: shipper.yml, when: '"ls_shipper" in group_names'}
