---
- name: Copy logstash parser configuration
  template: src=etc-logstash-parser.conf.j2 dest=/etc/logstash/conf.d/parser.conf owner=root group=root mode=0644
  tags:
    - logstash
    - config
    - parserconf
  notify: restart logstash

- name: Copy logstash patterns
  copy: src=patterns dest=/opt/logstash owner=root group=logreader mode=0640
  tags:
    - logstash
    - config
    - parserconf
    - patterns
  notify: restart logstash