- name: Configure Logstash repo
  include: ls_repo.yml

- name: Install and configure Logstash
  include: ls_setup.yml

- name: Configure parsing nodes
  include: parser.yml
  when: '"ls_parser" in group_names'

- name: Configure collector nodes
  include: collector.yml
  when: '"ls_collector" in group_names'
