---
- name: Install packages needed by Logstash
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.8.0-openjdk
  tags:
    - logstash

- include: ls_repo.yml
- include: ls_setup.yml
- { include: parser.yml, when: '"ls_parser" in group_names'}
- { include: collector.yml, when: '"ls_collector" in group_names'}
