---
- name: Copy shipper config
  template: src=etc-logstash-shipper.conf.j2
            dest=/etc/logstash/conf.d/shipper.conf
            owner=root
            group=root
            mode=0644
  tags: [ "logstash" , "config" , "shipperconf" ]
  notify: restart logstash

- name: Set heap size for logstash
  lineinfile: dest=/etc/sysconfig/logstash regexp='^(#)?LS_HEAP_SIZE=' line='LS_HEAP_SIZE="4096m"' state=present
  tags: [ "logstash" , "config" , "parserconf" ]
  notify: restart logstash