---
- name: Copy shipper config
  template: src=etc-logstash-shipper.conf.j2
            dest=/etc/logstash/conf.d/shipper.conf
            owner=root
            group=root
            mode=0644
  tags:
    - logstash
    - config
    - shipperconf
  notify: restart logstash