- name: PARSER | Copy logstash parser configuration
  template:
    src: parser.conf.j2
    dest: /etc/logstash/conf.d/parser.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - test logstash config
    - restart logstash
  tags:
    - logstash
    - ls-config
    - ls-parserconf

- name: PARSER | Copy logstash patterns
  copy:
    src: patterns
    dest: /opt/logstash/
    owner: logstash
    group: logreader
    mode: '0644'
    directory_mode: '0755'
  notify: restart logstash
  tags:
    - logstash
    - ls-config
    - ls-parserconf
    - ls-patterns
