---
- name: Copy logstash parser configuration
  template:
    src: parser.conf.j2
    dest: /etc/logstash/conf.d/parser.conf
    owner: root
    group: root
    mode: 0644
  tags: [ "logstash" , "config" , "parserconf" ]
  notify:
    - test logstash config
    - restart logstash

- name: Copy logstash patterns
  copy:
    src: patterns
    dest: /opt/logstash/
    owner: logstash
    group: logreader
    mode: 0644
    directory_mode: 0755
  tags: [ "logstash" , "config" , "parserconf" , "patterns" ]
  notify: restart logstash
