Vagrant.configure(2) do |config|

  # CentOS 6
  config.vm.define "ls-el6" do |centos6|
    centos6.vm.box = "samdoran/centos6"
    centos6.vm.hostname = "ls-centos6"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "ls-el6"
      vbox.cpus = 2
      vbox.memory = 512
    end
  end

  # CentOS 7
  config.vm.define "ls-el7" do |centos7|
    centos7.vm.box = "samdoran/centos7"
    centos7.vm.hostname = "ls-centos7"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "ls-el7"
      vbox.cpus = 2
      vbox.memory = 512
    end
  end

  # # Ubuntu 12.04
  # config.vm.define "ls-ub12" do |node|
  #   node.vm.box = "geerlingguy/ubuntu1204"
  #   node.vm.hostname = "ls-ub12"
  #   config.vm.provider "virtualbox" do |vbox|
  #     vbox.name = "ls-ub12"
  #     vbox.cpus = 1
  #     vbox.memory = 128
  #   end
  # end

  # # Ubuntu 14.04
  # config.vm.define "ls-ub14" do |ub14|
  #   ub14.vm.box = "geerlingguy/ubuntu1404"
  #   ub14.vm.hostname = "ls-ub14"
  #   config.vm.provider "virtualbox" do |vbox|
  #     vbox.name = "ls-ub14"
  #     vbox.cpus = 1
  #     vbox.memory = 128
  #   end
  # end

  # # Ubuntu 16.04
  # config.vm.define "ls-ub16" do |ub16|
  #   ub16.vm.box = "geerlingguy/ubuntu1604"
  #   ub16.vm.hostname = "ls-ub16"
  #   config.vm.provider "virtualbox" do |vbox|
  #     vbox.name = "ls-ub16"
  #     vbox.cpus = 1
  #     vbox.memory = 128
  #   end
  # end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
