---
# A bug in 2.3.0 broke the validation option
# https://github.com/elastic/logstash/issues/4933
- name: test logstash config
  command: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/ -t
  when: current_logstash_version.stdout != "2.3.0"

- name: restart logstash
  service:
    name: logstash
    state: restarted
